import localFont from "next/font/local";
import "./globals.css";
import Counter from "./counter";

// Import the Metadata type as a regular JavaScript import
import { Metadata } from "next"; // This can be removed if Metadata is not used directly in your JS project.

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>This is navigation bar</nav>
        {children}
        <Counter />
        <footer>This is footer</footer>
      </body>
    </html>
  );
}
