import localFont from "next/font/local";
import "./globals.css";

// Import the Metadata type as a regular JavaScript import
import { Metadata } from "next"; // This can be removed if Metadata is not used directly in your JS project.

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full h-[50px] bg-blue-300 border-2 border-blue-300">
          HEADER
        </header>
        {children}
        <footer className="w-full h-[50px] bg-gray-300 border-2 border-gray-300">
          FOOTER
        </footer>
      </body>
    </html>
  );
}
